version: '3.3'
services:
  node:
    container_name: dormhub_back-end
    build: .
    restart: always
    network_mode: bridge
    ports:
      - 3001:3001
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./static/kaoshoes:/app/static:shared
